[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "image-comparator"
version = "0.1.2"
description = "Compare sets of images side by side with keyboard navigation"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = "MIT"
authors = [
  { name = "Shashank Katiyar" }
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
]

dependencies = [
  "matplotlib",
  "numpy",
  "Pillow",
  "reportlab",
  "pymupdf",
]

[project.scripts]
image-comparator = "image_comparator.app:main"